# These are supported funding model platforms

# GitHub Sponsors (replace with your GitHub username)
github: [silversurfer562]

# Patreon (replace with your Patreon username)
patreon: # your-patreon-username

# Open Collective (replace with your Open Collective username)
open_collective: # ai-nurse-florence

# Ko-fi (replace with your Ko-fi username)
ko_fi: # your-kofi-username

# Tidelift (replace with your Tidelift package name)
tidelift: # npm/ai-nurse-florence

# Community Bridge (replace with your project name)
community_bridge: # ai-nurse-florence

# Liberapay (replace with your Liberapay username)
liberapay: # your-liberapay-username

# IssueHunt (replace with your IssueHunt username)
issuehunt: # your-issuehunt-username

# Custom funding URLs (you can add multiple)
custom: # Add your custom funding URLs here
  - https://paypal.me/yourname  # Replace 'yourname' with your PayPal.me username
  # - https://www.buymeacoffee.com/yourname
  # - https://www.gofundme.com/your-campaign
