[tool.ruff]
line-length = 88
target-version = "py310"
exclude = [
	"src/app_enhanced.py",
	"src\\app_enhanced.py",
	"temp_app_fix.py",
	"api/**",
	"artifacts/**",
	"backups/**",
	"src/data/**",
	"tests/**/fixtures/**"
]

[tool.ruff.lint]
ignore = ["E203"]
