[build]
builder = "nixpacks"

[deploy]
startCommand = "python -m uvicorn app:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "always"

[experimental]
configVersion = 2

[[services]]
name = "ai-nurse-florence"

[services.source]
repo = "silversurfer562/ai-nurse-florence"

[environments.production]
variables = { }
