[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
restartPolicyType = "on_failure"

[environments.production]
variables = { PORT = "8080" }

[environments.development]
variables = { }
