[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "gunicorn -k uvicorn.workers.UvicornWorker --workers 4 --bind 0.0.0.0:8080 --timeout 120 app:app"
restartPolicyType = "on_failure"

[environments.production]
variables = { }

[environments.development]
variables = { }
