#!/usr/bin/env python3
"""
Seed Medications Database - Autocomplete Only
AI Nurse Florence

Populates the medications table with 500+ medication names for autocomplete functionality.
This database is ONLY used for medication name search - NOT for drug details.
All drug interaction analysis and clinical information comes from OpenAI.
"""

import sys
import os
from pathlib import Path

# Add project root to path
project_root = Path(__file__).parent.parent
sys.path.insert(0, str(project_root))

import asyncio
import uuid
from datetime import datetime
from sqlalchemy.ext.asyncio import create_async_engine, AsyncSession
from sqlalchemy.orm import sessionmaker
from src.models.database import Medication, Base
from src.utils.config import Settings

# Comprehensive list of 500+ commonly prescribed medications (generic and brand names)
COMMON_MEDICATIONS = [
    "Lisinopril",
    "Amlodipine",
    "Metoprolol",
    "Atorvastatin",
    "Simvastatin",
    "Losartan",
    "Carvedilol",
    "Furosemide",
    "Hydrochlorothiazide",
    "Warfarin",
    "Clopidogrel",
    "Aspirin",
    "Ramipril",
    "Valsartan",
    "Diltiazem",
    "Enalapril",
    "Propranolol",
    "Spironolactone",
    "Digoxin",
    "Isosorbide",
    "Nifedipine",
    "Verapamil",
    "Quinapril",
    "Benazepril",
    "Fosinopril",
    "Telmisartan",
    "Irbesartan",
    "Candesartan",
    "Olmesartan",
    "Eplerenone",
    "Rosuvastatin",
    "Pravastatin",
    "Lovastatin",
    "Fluvastatin",
    "Pitavastatin",
    "Fenofibrate",
    "Gemfibrozil",
    "Ezetimibe",
    "Nitroglycerin",
    "Hydralazine",
    "Clonidine",
    "Doxazosin",
    "Prazosin",
    "Terazosin",
    "Labetalol",
    "Atenolol",
    "Nadolol",
    "Bisoprolol",
    "Nebivolol",
    "Acebutolol",
    "Lipitor",
    "Zocor",
    "Crestor",
    "Pravachol",
    "Mevacor",
    "Norvasc",
    "Cardizem",
    "Toprol",
    "Lopressor",
    "Coreg",
    "Lasix",
    "Coumadin",
    "Plavix",
    "Diovan",
    "Cozaar",
    "Prinivil",
    "Zestril",
    "Vasotec",
    "Altace",
    "Accupril",
    "Metformin",
    "Glipizide",
    "Glyburide",
    "Insulin",
    "Sitagliptin",
    "Pioglitazone",
    "Rosiglitazone",
    "Glimepiride",
    "Acarbose",
    "Repaglinide",
    "Nateglinide",
    "Exenatide",
    "Liraglutide",
    "Dulaglutide",
    "Semaglutide",
    "Canagliflozin",
    "Dapagliflozin",
    "Empagliflozin",
    "Ertugliflozin",
    "Saxagliptin",
    "Linagliptin",
    "Alogliptin",
    "Pramlintide",
    "Insulin Glargine",
    "Insulin Aspart",
    "Insulin Lispro",
    "Insulin Detemir",
    "Insulin Degludec",
    "NPH Insulin",
    "Regular Insulin",
    "Glucophage",
    "Januvia",
    "Actos",
    "Avandia",
    "Amaryl",
    "Victoza",
    "Ozempic",
    "Trulicity",
    "Byetta",
    "Invokana",
    "Farxiga",
    "Jardiance",
    "Lantus",
    "Humalog",
    "Novolog",
    "Levemir",
    "Tresiba",
    "Toujeo",
    "Basaglar",
    "Apidra",
    "Amoxicillin",
    "Azithromycin",
    "Ciprofloxacin",
    "Levofloxacin",
    "Doxycycline",
    "Cephalexin",
    "Clindamycin",
    "Metronidazole",
    "Trimethoprim",
    "Sulfamethoxazole",
    "Penicillin",
    "Ampicillin",
    "Cefuroxime",
    "Ceftriaxone",
    "Cefdinir",
    "Nitrofurantoin",
    "Vancomycin",
    "Gentamicin",
    "Tobramycin",
    "Moxifloxacin",
    "Clarithromycin",
    "Erythromycin",
    "Tetracycline",
    "Minocycline",
    "Linezolid",
    "Cefazolin",
    "Cefepime",
    "Ceftazidime",
    "Meropenem",
    "Imipenem",
    "Ertapenem",
    "Piperacillin",
    "Tazobactam",
    "Amoxicillin-Clavulanate",
    "Sulfadiazine",
    "Augmentin",
    "Zithromax",
    "Z-Pak",
    "Cipro",
    "Levaquin",
    "Keflex",
    "Cleocin",
    "Flagyl",
    "Bactrim",
    "Septra",
    "Avelox",
    "Biaxin",
    "Macrobid",
    "Rocephin",
    "Omnicef",
    "Ibuprofen",
    "Naproxen",
    "Acetaminophen",
    "Tramadol",
    "Celecoxib",
    "Meloxicam",
    "Diclofenac",
    "Indomethacin",
    "Ketorolac",
    "Piroxicam",
    "Hydrocodone",
    "Oxycodone",
    "Morphine",
    "Fentanyl",
    "Codeine",
    "Hydromorphone",
    "Oxymorphone",
    "Buprenorphine",
    "Naloxone",
    "Gabapentin",
    "Pregabalin",
    "Duloxetine",
    "Amitriptyline",
    "Nortriptyline",
    "Cyclobenzaprine",
    "Advil",
    "Motrin",
    "Aleve",
    "Tylenol",
    "Ultram",
    "Celebrex",
    "Mobic",
    "Voltaren",
    "Toradol",
    "Vicodin",
    "Percocet",
    "OxyContin",
    "Dilaudid",
    "Duragesic",
    "Suboxone",
    "Neurontin",
    "Lyrica",
    "Cymbalta",
    "Elavil",
    "Pamelor",
    "Flexeril",
    "Soma",
    "Robaxin",
    "Skelaxin",
    "Zanaflex",
    "Omeprazole",
    "Pantoprazole",
    "Esomeprazole",
    "Lansoprazole",
    "Rabeprazole",
    "Famotidine",
    "Ranitidine",
    "Ondansetron",
    "Metoclopramide",
    "Bismuth",
    "Loperamide",
    "Docusate",
    "Senna",
    "Polyethylene Glycol",
    "Lactulose",
    "Psyllium",
    "Sucralfate",
    "Misoprostol",
    "Mesalamine",
    "Sulfasalazine",
    "Dicyclomine",
    "Hyoscyamine",
    "Lubiprostone",
    "Linaclotide",
    "Eluxadoline",
    "Prilosec",
    "Protonix",
    "Nexium",
    "Prevacid",
    "AcipHex",
    "Pepcid",
    "Zantac",
    "Zofran",
    "Reglan",
    "Pepto-Bismol",
    "Imodium",
    "Colace",
    "Senokot",
    "MiraLAX",
    "Metamucil",
    "Carafate",
    "Cytotec",
    "Asacol",
    "Azulfidine",
    "Bentyl",
    "Albuterol",
    "Fluticasone",
    "Budesonide",
    "Montelukast",
    "Ipratropium",
    "Tiotropium",
    "Salmeterol",
    "Formoterol",
    "Prednisone",
    "Methylprednisolone",
    "Dexamethasone",
    "Guaifenesin",
    "Dextromethorphan",
    "Benzonatate",
    "Cetirizine",
    "Loratadine",
    "Fexofenadine",
    "Diphenhydramine",
    "Pseudoephedrine",
    "Phenylephrine",
    "Oxymetazoline",
    "Cromolyn",
    "Zafirlukast",
    "Roflumilast",
    "Proventil",
    "Ventolin",
    "ProAir",
    "Flovent",
    "Pulmicort",
    "Singulair",
    "Atrovent",
    "Spiriva",
    "Advair",
    "Symbicort",
    "Breo",
    "Anoro",
    "Dulera",
    "Mucinex",
    "Robitussin",
    "Tessalon",
    "Zyrtec",
    "Claritin",
    "Allegra",
    "Benadryl",
    "Sudafed",
    "Afrin",
    "Nasacort",
    "Flonase",
    "Rhinocort",
    "Sertraline",
    "Fluoxetine",
    "Escitalopram",
    "Citalopram",
    "Paroxetine",
    "Venlafaxine",
    "Desvenlafaxine",
    "Bupropion",
    "Mirtazapine",
    "Trazodone",
    "Buspirone",
    "Alprazolam",
    "Lorazepam",
    "Clonazepam",
    "Diazepam",
    "Temazepam",
    "Zolpidem",
    "Eszopiclone",
    "Ramelteon",
    "Quetiapine",
    "Olanzapine",
    "Risperidone",
    "Aripiprazole",
    "Ziprasidone",
    "Lithium",
    "Valproic Acid",
    "Lamotrigine",
    "Carbamazepine",
    "Oxcarbazepine",
    "Atomoxetine",
    "Methylphenidate",
    "Amphetamine",
    "Lisdexamfetamine",
    "Dextroamphetamine",
    "Modafinil",
    "Armodafinil",
    "Memantine",
    "Donepezil",
    "Rivastigmine",
    "Galantamine",
    "Varenicline",
    "Naltrexone",
    "Disulfiram",
    "Zoloft",
    "Prozac",
    "Lexapro",
    "Celexa",
    "Paxil",
    "Effexor",
    "Pristiq",
    "Wellbutrin",
    "Remeron",
    "Desyrel",
    "BuSpar",
    "Xanax",
    "Ativan",
    "Klonopin",
    "Valium",
    "Restoril",
    "Ambien",
    "Lunesta",
    "Rozerem",
    "Seroquel",
    "Zyprexa",
    "Risperdal",
    "Abilify",
    "Geodon",
    "Eskalith",
    "Depakote",
    "Lamictal",
    "Tegretol",
    "Trileptal",
    "Strattera",
    "Ritalin",
    "Concerta",
    "Adderall",
    "Vyvanse",
    "Provigil",
    "Nuvigil",
    "Namenda",
    "Aricept",
    "Exelon",
    "Razadyne",
    "Chantix",
    "Zyban",
    "Antabuse",
    "Campral",
    "Levothyroxine",
    "Liothyronine",
    "Methimazole",
    "Propylthiouracil",
    "Testosterone",
    "Estradiol",
    "Progesterone",
    "Medroxyprogesterone",
    "Norethindrone",
    "Ethinyl Estradiol",
    "Levonorgestrel",
    "Desogestrel",
    "Drospirenone",
    "Tamoxifen",
    "Raloxifene",
    "Alendronate",
    "Risedronate",
    "Ibandronate",
    "Zoledronic Acid",
    "Calcitonin",
    "Teriparatide",
    "Denosumab",
    "Vitamin D",
    "Calcium",
    "Calcitriol",
    "Synthroid",
    "Levoxyl",
    "Cytomel",
    "Tapazole",
    "PTU",
    "AndroGel",
    "Testim",
    "Estrace",
    "Premarin",
    "Provera",
    "Depo-Provera",
    "Ortho-Novum",
    "Yasmin",
    "Yaz",
    "NuvaRing",
    "Plan B",
    "Nolvadex",
    "Evista",
    "Fosamax",
    "Actonel",
    "Boniva",
    "Reclast",
    "Miacalcin",
    "Forteo",
    "Prolia",
    "Heparin",
    "Enoxaparin",
    "Rivaroxaban",
    "Apixaban",
    "Dabigatran",
    "Edoxaban",
    "Prasugrel",
    "Ticagrelor",
    "Dipyridamole",
    "Cilostazol",
    "Fondaparinux",
    "Argatroban",
    "Lovenox",
    "Xarelto",
    "Eliquis",
    "Pradaxa",
    "Savaysa",
    "Effient",
    "Brilinta",
    "Aggrenox",
    "Pletal",
    "Arixtra",
    "Fragmin",
    "Innohep",
    "Angiomax",
    "Levodopa",
    "Carbidopa",
    "Pramipexole",
    "Ropinirole",
    "Amantadine",
    "Phenytoin",
    "Levetiracetam",
    "Topiramate",
    "Lacosamide",
    "Sumatriptan",
    "Rizatriptan",
    "Eletriptan",
    "Zolmitriptan",
    "Baclofen",
    "Tizanidine",
    "Dantrolene",
    "Sinemet",
    "Mirapex",
    "Requip",
    "Symmetrel",
    "Dilantin",
    "Keppra",
    "Topamax",
    "Vimpat",
    "Imitrex",
    "Maxalt",
    "Relpax",
    "Zomig",
    "Inderal",
    "Lioresal",
    "Dantrium",
    "Hydrocortisone",
    "Azathioprine",
    "Cyclosporine",
    "Tacrolimus",
    "Mycophenolate",
    "Methotrexate",
    "Hydroxychloroquine",
    "Leflunomide",
    "Adalimumab",
    "Etanercept",
    "Infliximab",
    "Rituximab",
    "Tocilizumab",
    "Ustekinumab",
    "Secukinumab",
    "Ixekizumab",
    "Deltasone",
    "Medrol",
    "Cortef",
    "Decadron",
    "Imuran",
    "Neoral",
    "Sandimmune",
    "Prograf",
    "CellCept",
    "Rheumatrex",
    "Plaquenil",
    "Arava",
    "Humira",
    "Enbrel",
    "Remicade",
    "Rituxan",
    "Actemra",
    "Stelara",
    "Cosentyx",
    "Taltz",
    "Simponi",
    "Cimzia",
    "Orencia",
    "Kineret",
    "Tamsulosin",
    "Finasteride",
    "Dutasteride",
    "Alfuzosin",
    "Sildenafil",
    "Tadalafil",
    "Vardenafil",
    "Oxybutynin",
    "Tolterodine",
    "Solifenacin",
    "Darifenacin",
    "Fesoterodine",
    "Mirabegron",
    "Flomax",
    "Proscar",
    "Propecia",
    "Avodart",
    "Uroxatral",
    "Cardura",
    "Hytrin",
    "Viagra",
    "Cialis",
    "Levitra",
    "Ditropan",
    "Detrol",
    "VESIcare",
    "Enablex",
    "Toviaz",
    "Myrbetriq",
    "Rapaflo",
    "Jalyn",
    "Combigan",
    "Betoptic",
    "Latanoprost",
    "Timolol",
    "Brimonidine",
    "Dorzolamide",
    "Brinzolamide",
    "Travoprost",
    "Bimatoprost",
    "Tafluprost",
    "Prednisolone",
    "Loteprednol",
    "Nepafenac",
    "Bromfenac",
    "Xalatan",
    "Timoptic",
    "Alphagan",
    "Trusopt",
    "Azopt",
    "Travatan",
    "Lumigan",
    "Zioptan",
    "Pred Forte",
    "Restasis",
    "Lotemax",
    "Acular",
    "Nevanac",
    "Prolensa",
    "Ilevro",
    "Tretinoin",
    "Isotretinoin",
    "Adapalene",
    "Benzoyl Peroxide",
    "Triamcinolone",
    "Betamethasone",
    "Clobetasol",
    "Fluocinonide",
    "Pimecrolimus",
    "Retin-A",
    "Accutane",
    "Differin",
    "Benzac",
    "Cleocin T",
    "Ery-Tab",
    "Doryx",
    "Solodyn",
    "Cortaid",
    "Kenalog",
    "Diprolene",
    "Temovate",
    "Lidex",
    "Protopic",
    "Elidel",
    "Acyclovir",
    "Valacyclovir",
    "Famciclovir",
    "Oseltamivir",
    "Zanamivir",
    "Rimantadine",
    "Ribavirin",
    "Sofosbuvir",
    "Ledipasvir",
    "Daclatasvir",
    "Simeprevir",
    "Ombitasvir",
    "Paritaprevir",
    "Dasabuvir",
    "Tenofovir",
    "Emtricitabine",
    "Lamivudine",
    "Efavirenz",
    "Dolutegravir",
    "Raltegravir",
    "Elvitegravir",
    "Atazanavir",
    "Darunavir",
    "Lopinavir",
    "Ritonavir",
    "Abacavir",
    "Zidovudine",
    "Stavudine",
    "Didanosine",
    "Zovirax",
    "Valtrex",
    "Famvir",
    "Tamiflu",
    "Relenza",
    "Flumadine",
    "Rebetol",
    "Sovaldi",
    "Harvoni",
    "Daklinza",
    "Olysio",
    "Viekira Pak",
    "Viread",
    "Truvada",
    "Epivir",
    "Sustiva",
    "Tivicay",
    "Isentress",
    "Vitekta",
    "Reyataz",
    "Prezista",
    "Kaletra",
    "Ziagen",
    "Retrovir",
    "Allopurinol",
    "Colchicine",
    "Probenecid",
    "Febuxostat",
    "Rasburicase",
    "Cholestyramine",
    "Colesevelam",
    "Niacin",
    "Fish Oil",
    "Omega-3",
    "Vitamin B12",
    "Folic Acid",
    "Iron",
    "Ferrous Sulfate",
    "Multivitamin",
    "Potassium",
    "Magnesium",
    "Zinc",
    "Biotin",
    "Vitamin C"
]

async def seed_medications():
    """Seed the medications database with common medication names for autocomplete."""
    settings = Settings()

    # Handle both SQLite and PostgreSQL
    db_url = settings.DATABASE_URL
    if 'postgresql://' in db_url:
        db_url = db_url.replace('postgresql://', 'postgresql+asyncpg://')
    elif 'sqlite' not in db_url:
        # Default to SQLite if no database configured
        db_url = 'sqlite+aiosqlite:///./dev.db'

    print(f"Connecting to database: {db_url.split('@')[0]}...")  # Hide credentials

    # Create async engine
    engine = create_async_engine(db_url, echo=False)

    # Create tables
    async with engine.begin() as conn:
        await conn.run_sync(Base.metadata.create_all)

    # Create session
    async_session = sessionmaker(
        engine, class_=AsyncSession, expire_on_commit=False
    )

    async with async_session() as session:
        # Clear existing medications
        from sqlalchemy import text
        await session.execute(text("DELETE FROM medications"))
        await session.commit()

        print(f"Adding {len(COMMON_MEDICATIONS)} medications to database...")

        # Add medications (use executemany for better performance and avoid duplicates)
        medications_added = 0
        for med_name in COMMON_MEDICATIONS:
            # Check if medication already exists (case-insensitive)
            from sqlalchemy import select, func
            result = await session.execute(
                select(Medication).where(func.lower(Medication.name) == func.lower(med_name))
            )
            existing = result.scalar_one_or_none()

            if not existing:
                medication = Medication(
                    id=str(uuid.uuid4()),
                    name=med_name,
                    source="curated_autocomplete",
                    is_active=True,
                    created_at=datetime.utcnow(),
                    updated_at=datetime.utcnow()
                )
                session.add(medication)
                medications_added += 1

                if medications_added % 50 == 0:
                    print(f"  Added {medications_added} medications...")
                    await session.commit()  # Commit in batches

        await session.commit()  # Final commit
        print(f"\n✅ Successfully added {medications_added} medications to database")
        print("Database is now ready for autocomplete functionality")

    await engine.dispose()

if __name__ == "__main__":
    print("=" * 70)
    print("AI Nurse Florence - Medication Autocomplete Database Seeding")
    print("=" * 70)
    print("\nThis script populates the medications table with 500+ medication names")
    print("for autocomplete functionality ONLY.")
    print("\nNote: Drug interaction analysis and clinical details come from OpenAI,")
    print("      NOT from this database.")
    print("=" * 70)
    print()

    asyncio.run(seed_medications())
